Update pr_list.yml

diff --git a/.github/workflows/pr_list.yml b/.github/workflows/pr_list.yml
--- a/.github/workflows/pr_list.yml
+++ b/.github/workflows/pr_list.yml
@@ -8,28 +8,38 @@ on:
     workflow_dispatch:
 
 jobs:
-    list_of_PRs:
-        runs-on: [ubuntu-latest]
-
+    create-issue-gh-cli:
+        runs-on: ubuntu-latest
         steps:
-            - name: Checkout repository
-              uses: actions/checkout@v2
-              with:
-                ref: ${{ github.ref }}
-                
-            - name: Authenticating for GitHub
-              env:
-               STAGE: dev
-               GH_PAT: ${{ secrets.TOKEN_GITHUB }}
-              run: |
-                gh auth login --with-token <<<"${{ secrets.GH_PAT }}"
-                gh pr list --author sqali > pull_requests_list.txt
-                cat pull_requests_list.txt
+        
+        - name: Checks out repo
+          uses: actions/checkout@v2
+          
+        - name: Installing GitHub CLI if not present in the system
+          # Installing github cli if not installed
+          run: |
+            if ! command -v gh &> /dev/null; then 
+                echo "GitHub CLI not found. Installing..."
+                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
+                sudo apt-add-repository https://cli.github.com/packages
+                sudo apt update
+                sudo apt install gh
+            fi
+            
+        - name: Authentication with GitHub using PAT
+          run: |
+              echo "Authenticating with GitHub using Personal Access Token"
+              gh auth login --with-token <<< "${{ secrets.GH_PAT }}"
+              
+        - name: Fetching all pull requests
+          run: |
+              gh pr list --author sqali > pull_requests_list.txt
+              cat pull_requests_list.txt
 
-            - name: Upload a Build Artifact
-              uses: actions/upload-artifact@v3.1.3
-              with:
-                name: pull_requests_list
-                path: pull_requests_list.txt
+        - name: Upload a Build Artifact
+          uses: actions/upload-artifact@v3.1.3
+          with:
+            name: pull_requests_list
+            path: pull_requests_list.txt
         
         # Checkout the code and use the python file to filter out the PR list
